### ISSUE TITLE
MultiDocWebChat.py", line 165, AttributeError: module 'streamlit' has no attribute 'chat_input'

### ISSUE THREAD

**Issue by HyperUpscale** [Chandru-21/MultiDocWebChat#1]
**streamlit run MultiDocWebChat.py**

  ```
You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.0.189:8501

2023-10-02 18:59:05.942 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\super\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)

 File "MultiDocWebChat.py", line 165, in <module>
    user_question =st.chat_input("Ask a question about your documents:")
AttributeError: module 'streamlit' has no attribute 'chat_input'
```

**Comment by Chandru-21** [comment]
Use the latest version of streamlit.
pip install --upgrade streamlit

**Comment by HyperUpscale** [comment]
Nope.

I solved with 
`pip install streamlit_chat`

**Comment by HyperUpscale** [comment]
I am new to github so I am not sure how to suggest commit to you.
Just a recommendation for requirements.txt to edit: 

+ PyCryptodome
+ streamlit_chat
+ google-search-results

:)

**Comment by Chandru-21** [comment]
Apologies,I had all these pre-installed. So,couldn't properly put them in requirements.txt.
I understand this project needs streamlit_chat for user-Bot conversation, google-search-results and google-serp-api for enabling google search but not sure about PyCryptodome because I haven't used that library nor is it installed in my local.

Anyways, thanks for the suggestion.
I'll add the necessary libs in requirements.txt.

**Comment by HyperUpscale** [comment]
I uploaded one PDF and it asked me for that PyCryptodome dependency - maybe it had a password or protection (not sure)... :) 

"...entering pdf
2023-10-06 12:39:38.110 Uncaught app exception
Traceback (most recent call last):
  File "D:\TRIAL\MultiDocWebChat\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "D:\TRIAL\MultiDocWebChat\MultiDocWebChat.py", line 176, in <module>
    raw_text=get_pdf_text(pdf_docs)
  File "D:\TRIAL\MultiDocWebChat\MultiDocWebChat.py", line 46, in get_pdf_text
    pdf_reader = PdfReader(pdf)
  File "D:\TRIAL\MultiDocWebChat\lib\site-packages\PyPDF2\_reader.py", line 339, in __init__
    self._encryption.verify(pwd) == PasswordType.NOT_DECRYPTED
  File "D:\TRIAL\MultiDocWebChat\lib\site-packages\PyPDF2\_encryption.py", line 785, in verify
    key, rc = self.verify_v4(pwd) if self.algV <= 4 else self.verify_v5(pwd)
  File "D:\TRIAL\MultiDocWebChat\lib\site-packages\PyPDF2\_encryption.py", line 836, in verify_v5
    key = AlgV5.verify_owner_password(
  File "D:\TRIAL\MultiDocWebChat\lib\site-packages\PyPDF2\_encryption.py", line 530, in verify_owner_password
    AlgV5.calculate_hash(R, password, o_value[32:40], u_value[:48])
  File "D:\TRIAL\MultiDocWebChat\lib\site-packages\PyPDF2\_encryption.py", line 561, in calculate_hash
    E = AES_CBC_encrypt(K[:16], K[16:32], K1 * 64)
  File "D:\TRIAL\MultiDocWebChat\lib\site-packages\PyPDF2\_encryption.py", line 162, in AES_CBC_encrypt
    raise DependencyError("PyCryptodome is required for AES algorithm")
PyPDF2.errors.DependencyError: **PyCryptodome is required for AES algorithm**
  Stopping...
  "

**Comment by Chandru-21** [comment]
Yea that might be the reason!
